import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { dir } from 'i18next'
import { languages } from '../i18n/settings';
import { Footer } from './components/Footer/client';
import Favicon from '/public/favicon.ico';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Spelling Bee',
  description: 'Generated by MORS',
  icons: [{ rel: 'icon', url: Favicon.src }],
}


export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default function RootLayout({ children, params: {
  lng
} }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      
      <body className={inter.className}>
      <Footer lng={lng}/>{children}
      <ToastContainer 
      position="top-right"
      autoClose={1200}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}     
      draggable  
      theme="light"
       /></body>
    </html>
  )
}
